name: Sync Labels
on:
  issues: 
    types:
      - opened
      - labeled
  pull_request:

# Declare default permissions as read only.
permissions: read-all

jobs:
  scorecard:
    uses: outoforbitdev/.github/.github/workflows/labels.yml@main
    permissions:
      issues: write
      actions: read
      attestations: read
      checks: read
      contents: read
      deployments: read
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      statuses: read
      security-events: read
      id-token: read
      
