name: NPM Publish
permissions: read-all
on:
  release:
    types: [published]
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    name: Publish Package
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci --include=dev
      - run: npm run build
      - run: npm publish --provenance --access public
