name: Release App
permissions: read-all
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
    paths:
      - CHANGELOG.md
  pull_request:
    paths:
      - CHANGELOG.md
jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish Github Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python dependencies
        run: python -m pip install requests
      - name: Run release script
        run: python ci/create_release.py ${{secrets.GITHUB_TOKEN}}
