name: Release
permissions: read-all
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
    paths:
      - CHANGELOG.md
jobs:
  check-release-match:
    runs-on: ubuntu-latest
    name: Check Release Versions Match
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.10'
      - name: Compare versions
        run: python ci/check_versions.py
  release:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    name: Publish Github Release
    needs: check-release-match
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: python -m pip install requests
      - name: Run release script
        run: python ci/create_release.py ${{secrets.GITHUB_TOKEN}}
