name: Release App
permissions: read-all
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
    paths:
      - CHANGELOG.md
  pull_request:
    paths:
      - CHANGELOG.md
jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish Github Release
    outputs:
      version-released: ${{ steps.semantic-release.outputs.version-released }}
      next-version: ${{ steps.semantic-release.outputs.next-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Publish Release
        id: semantic-release
        shell: python
        run: |
          from ci import create_release
          create_release.release_version(${{secrets.GITHUB_TOKEN}})
