name: Release App
permissions: read-all
on:
  push:
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  release:
    runs-on: ubuntu-latest
    name: Publish Github Release
    outputs:
      version-released: ${{ steps.semantic-release.outputs.version-released }}
      next-version: ${{ steps.semantic-release.outputs.next-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Publish Release
        uses: outoforbitdev/action-semantic-release@v1.6.2
        id: semantic-release
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          skip-changelog: ${{ github.ref_name != 'main' }}
  publish-aspnet:
    runs-on: ubuntu-latest
    name: Publish Package
    needs:
      - release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
